/**
 * The Connector Proxy — a standalone Hono server. Spawned by `ahamie dev`
 * as a child process so the agent runtime and the credential layer run in
 * separate process spaces (T8: cannot accidentally share memory with model
 * stack traces or stdout dumps).
 *
 * Mounts:
 *   POST  /v1/forward                  — forward an HTTP call to an upstream connector
 *   POST  /v1/grants                   — issue a grant
 *   DELETE /v1/grants/:id              — revoke a grant
 *   POST  /v1/webhooks/:provider/:id   — inbound HMAC-verified webhook
 *   GET   /v1/mcp/:connectorId/tools   — MCP tool listing (runs *inside* proxy)
 *   POST  /v1/mcp/:connectorId/call    — invoke an MCP tool
 *   GET   /healthz                     — health check
 *
 * Authn: a per-launch bearer token in `Authorization: Bearer …`. The token
 * is generated by `ahamie dev` and passed to the agent process as
 * `AHAMIE_PROXY_TOKEN`. Without a valid bearer the proxy returns 401.
 */

import { Hono } from "hono";
import { eq } from "drizzle-orm";
import {
  asBrand,
  mintGrantId,
  type ConnectorId,
  type GrantId,
  type ManifestId,
  type OrgId,
} from "@ahamie/schema";
import { connector_grants, connectors, type AhamieDb } from "@ahamie/storage";
import { writeAudit } from "./audit";
import {
  type AllowlistEntry,
  compileAllowlist,
  InvariantViolationError,
  requireAllowlist,
  stripCallerAuth,
  stripResponseAuth,
  verifyHmac,
} from "./invariants";
import type { CredentialResolver } from "./credentials";

export interface ProxyAdapterRegistration {
  /** Provider id, e.g. `slack`, `github`. */
  provider: string;
  /** Allowlist (method + path). Allowlist linter (CI) walks this. */
  allowlist: AllowlistEntry[];
  /** Base URL for upstream calls. */
  baseUrl: string;
  /** How to apply the resolved token to the request — `bearer` or `header:X-Foo`. */
  authMode: "bearer" | { header: string };
  /** HMAC config for inbound webhooks. */
  inbound?: {
    signatureHeader: string;
    secretEnvVar: string;
    algo?: "sha256" | "sha1";
    prefix?: string;
    /** Lookup function: provider-supplied delivery ID for dedupe. */
    deliveryIdHeader?: string;
  };
}

export interface ProxyConfig {
  db: AhamieDb;
  credentialResolver: CredentialResolver;
  /** Per-launch bearer expected on every call. */
  bearer: string;
  /** Adapters keyed by provider id. */
  adapters: ProxyAdapterRegistration[];
  /** Optional fetch override (test injection). */
  fetchImpl?: typeof fetch;
}

export interface ForwardBody {
  orgId: OrgId;
  connectorId: string;
  method: string;
  path: string;
  body?: unknown;
  headers?: Record<string, string>;
}

export const createProxyApp = (cfg: ProxyConfig): Hono => {
  const app = new Hono();
  const fetchImpl = cfg.fetchImpl ?? fetch;
  const adapterIndex = new Map(cfg.adapters.map((a) => [a.provider, a] as const));
  const compiled = new Map(
    cfg.adapters.map((a) => [a.provider, compileAllowlist(a.allowlist)] as const),
  );

  app.use("*", async (c, next) => {
    if (c.req.path === "/healthz") return next();
    const auth = c.req.header("authorization") ?? "";
    if (auth !== `Bearer ${cfg.bearer}`) {
      return c.json({ error: "unauthorized" }, 401);
    }
    await next();
  });

  app.get("/healthz", (c) => c.json({ ok: true }));

  app.post("/v1/forward", async (c) => {
    const body = (await c.req.json()) as ForwardBody;
    const conn = (
      await cfg.db
        .select()
        .from(connectors)
        .where(eq(connectors.id, asBrand<"ConnectorId">(body.connectorId)))
        .limit(1)
    )[0];
    if (!conn) return c.json({ error: "connector_not_found" }, 404);
    if (conn.org_id !== body.orgId) return c.json({ error: "cross_tenant" }, 403);

    const adapter = adapterIndex.get(conn.provider);
    if (!adapter) return c.json({ error: "no_adapter" }, 400);
    const allowlist = compiled.get(conn.provider);
    if (!allowlist) return c.json({ error: "no_allowlist" }, 400);

    try {
      requireAllowlist(allowlist, body.method, body.path);
    } catch (e) {
      const err = e as InvariantViolationError;
      await writeAudit(cfg.db, {
        orgId: body.orgId,
        source: "proxy",
        action: "proxy.forward.denied",
        outcome: "denied",
        resource_kind: "connector",
        resource_id: conn.id,
        redaction_safe: {
          provider: conn.provider,
          method: body.method,
          path: body.path,
          invariant: err.invariant,
        },
      });
      return c.json({ error: "not_allowlisted" }, 403);
    }

    const token = await cfg.credentialResolver.resolve(body.connectorId);
    if (!token) return c.json({ error: "credential_missing" }, 412);

    // I3 — strip caller auth headers first, then add upstream auth.
    const reqHeaders = stripCallerAuth(new Headers(body.headers ?? {}));
    if (adapter.authMode === "bearer") {
      reqHeaders.set("authorization", `Bearer ${token}`);
    } else {
      reqHeaders.set(adapter.authMode.header, token);
    }

    const url = new URL(body.path, adapter.baseUrl);
    const upstream = await fetchImpl(url, {
      method: body.method,
      headers: reqHeaders,
      body: body.body == null ? undefined : JSON.stringify(body.body),
    });

    // I4 — strip auth-bearing response headers before returning to caller.
    const safeHeaders = stripResponseAuth(upstream.headers);
    const text = await upstream.text();

    await writeAudit(cfg.db, {
      orgId: body.orgId,
      source: "proxy",
      action: "proxy.forward",
      outcome: upstream.ok ? "success" : "error",
      resource_kind: "connector",
      resource_id: conn.id,
      redaction_safe: {
        provider: conn.provider,
        method: body.method,
        path: body.path,
        upstream_status: upstream.status,
      },
    });

    return new Response(text, {
      status: upstream.status,
      headers: safeHeaders,
    });
  });

  app.post("/v1/grants", async (c) => {
    const body = (await c.req.json()) as {
      orgId: OrgId;
      manifestId: string;
      connectorId: string;
      scopes: string[];
    };
    const id = mintGrantId();
    await cfg.db.insert(connector_grants).values({
      id,
      org_id: body.orgId,
      manifest_id: asBrand<"ManifestId">(body.manifestId),
      connector_id: asBrand<"ConnectorId">(body.connectorId),
      scopes: body.scopes,
    });
    await writeAudit(cfg.db, {
      orgId: body.orgId,
      source: "proxy",
      action: "proxy.grant",
      outcome: "success",
      resource_kind: "connector",
      resource_id: body.connectorId,
      redaction_safe: { manifest_id: body.manifestId, scopes: body.scopes },
    });
    return c.json({ id });
  });

  app.delete("/v1/grants/:id", async (c) => {
    const grantId = c.req.param("id");
    const orgId = c.req.header("x-ahamie-org") as OrgId | undefined;
    if (!orgId) return c.json({ error: "missing_org" }, 400);
    await cfg.db
      .update(connector_grants)
      .set({ revoked_at: new Date() })
      .where(eq(connector_grants.id, asBrand<"GrantId">(grantId)));
    await writeAudit(cfg.db, {
      orgId,
      source: "proxy",
      action: "proxy.revoke",
      outcome: "success",
      resource_kind: "grant",
      resource_id: grantId,
      redaction_safe: {},
    });
    return c.json({ revoked: grantId });
  });

  app.post("/v1/webhooks/:provider/:connectorId", async (c) => {
    const provider = c.req.param("provider");
    const connectorId = c.req.param("connectorId");
    const adapter = adapterIndex.get(provider);
    if (!adapter || !adapter.inbound) return c.json({ error: "no_adapter" }, 400);

    const conn = (
      await cfg.db
        .select()
        .from(connectors)
        .where(eq(connectors.id, asBrand<"ConnectorId">(connectorId)))
        .limit(1)
    )[0];
    if (!conn) return c.json({ error: "connector_not_found" }, 404);

    const raw = await c.req.text();
    const sig = c.req.header(adapter.inbound.signatureHeader) ?? "";
    const secret = process.env[adapter.inbound.secretEnvVar] ?? "";
    const ok = verifyHmac({
      secret,
      algo: adapter.inbound.algo ?? "sha256",
      body: raw,
      signature: sig,
      prefix: adapter.inbound.prefix ?? "",
    });

    if (!ok) {
      await writeAudit(cfg.db, {
        orgId: conn.org_id,
        source: "proxy",
        action: "proxy.webhook.rejected_hmac",
        outcome: "denied",
        resource_kind: "connector",
        resource_id: conn.id,
        redaction_safe: { provider },
      });
      return c.json({ error: "hmac_mismatch" }, 401);
    }

    await writeAudit(cfg.db, {
      orgId: conn.org_id,
      source: "proxy",
      action: "proxy.webhook.accepted",
      outcome: "success",
      resource_kind: "connector",
      resource_id: conn.id,
      redaction_safe: { provider },
    });
    return c.json({ accepted: true });
  });

  app.get("/v1/mcp/:connectorId/tools", async (c) => {
    // MCP runs *inside* the proxy (T8). v0 returns a stub list; the
    // production implementation wires `@mastra/mcp` `MCPClient` into the
    // proxy process. Tools never leak credentials — the agent only sees
    // tool names + JSON schemas.
    return c.json({ tools: [] });
  });

  app.post("/v1/mcp/:connectorId/call", async (c) => {
    return c.json({ error: "not_implemented_v0" }, 501);
  });

  return app;
};
